### ISSUE TITLE
прошился используя файл .bin

### ISSUE THREAD

**Issue by dinovasya** [tretyakovsa/Sonoff_WiFi_switch#1]
Прошился- заметил что светодиод встроенный не работает- не показывает никакой индикации.
Прохожу по адресу 192.168.4.1
Открывается страница с текстом: File not found

**Comment by renat2985** [comment]
Видимо вы не залили файловую систему, файлы с папки data.
![_086](https://cloud.githubusercontent.com/assets/1230815/20860033/84a5a684-b977-11e6-8584-b99ba8ba2b68.png)

**Comment by dinovasya** [comment]
всё верно
