### ISSUE TITLE
MAC адреса

### ISSUE THREAD

**Issue by Sergey-SRG** [tretyakovsa/Sonoff_WiFi_switch#10]
Можете ответить зачем вам база мак адресов?
http://backup.privet.lv/visitors.php?

**Comment by renat2985** [comment]
Это дает нам понять сколько людей пользуется нашими проектами и стоит ли в дальнейшем их развивать, или это зря потраченное время и нужно переключатся на что-то другое.

**Comment by tretyakovsa** [comment]
Сами мак адреса нам точно не нужны. Смотрим сколько раз используется прошивка.
