### ISSUE TITLE
Не срабатывает pir сенсор

### ISSUE THREAD

**Issue by 2007-i** [tretyakovsa/Sonoff_WiFi_switch#19]
Здравствуйте.
Прошился последней версией прошивки от 17.05 и при подключении датчика движения (да и просто подачи логических 1 и 0) на 12 пин реле никак не реагирует. В настройке датчика движения установил 1 сек.
Скажите я все правильно делаю и работает ли эта функция?

P.S. спасибо за вашу работу!

**Comment by renat2985** [comment]
PIR сенсор пока не работает. Но я думаю мы сделаем его в течение месяца, максимум двух. Сейчас работаем над другими задачами.
