### ISSUE TITLE
Please add Ukrainian language 

### ISSUE THREAD

**Issue by symparua** [tretyakovsa/Sonoff_WiFi_switch#22]
https://github.com/symparua/Sonoff_WiFi_switch/blob/master/lang.ua.json.gz

**Comment by renat2985** [comment]
Спасибо. Но ваш архив у меня не открывается должным образом. Пришлите lang.ua.json
Он должен быть такого формата: [https://github.com/tretyakovsa/Sonoff_WiFi_switch/blob/master/dev_data/lang/lang.ru.json](https://github.com/tretyakovsa/Sonoff_WiFi_switch/blob/master/dev_data/lang/lang.ru.json)

**Comment by symparua** [comment]
Исправил формат.
https://github.com/symparua/Sonoff_WiFi_switch/blob/master/lang.ua.json
Теперь норм?

**Comment by renat2985** [comment]
Спасибо. Добавили.

**Comment by AVL4GITHUB** [comment]
Дякую за українську мову!
Героям Слава!
