### ISSUE TITLE
edi и edit_new

### ISSUE THREAD

**Issue by dinovasya** [tretyakovsa/Sonoff_WiFi_switch#3]
Хотелось бы чтоб по ссылке Edit по умолчанию открывалась страница edit_new.htm а не edit.htm
Новая действительно лучше и открывается отлично теперь и на телефоне

**Comment by renat2985** [comment]
edit_new.htm - пока еще тестируем. Заменим думаю в ближайшие месяцы.

**Comment by dinovasya** [comment]
понятно. надо будет и ручками адрес введу edit_new.htm - не проблема. надобность редко возникнет, для обновления прошивки разве только иногда
