### ISSUE TITLE
Ошибка 403 в веб-интерфейсе при входе с другого устройства

### ISSUE THREAD

**Issue by shady2k** [tretyakovsa/Sonoff_WiFi_switch#59]
Вхожу с компьютера в веб-интерфейс, все хорошо, страничка отображается. Затем пытаюсь открыть веб-интерфейс с ноутбука или с телефона, ошибка 403 Forbidden, говорит nginx. Мне нужно как-то выходить с одного устройства прежде чем открывать на другом? Если да, то это как-то не очень хорошо. Или я что-то не так делаю?

**Comment by renat2985** [comment]
Насколько я понимаю эта проблема у вас на странице "Starting log"?
Такое очень редко но бывает. Просто попробуйте позже открыть и все будет хорошо.

**Comment by shady2k** [comment]
Нет, стартовая страница. То есть, я вообще не указываю страницу, только IP. Вот скрин с телефона. Ожидание не помогает.
![image-1 493](https://user-images.githubusercontent.com/3366415/32164018-3fa38266-bd6f-11e7-92d9-ef4add4262f8.jpg)

**Comment by renat2985** [comment]
Этот IP принадлежит не ESP. Он принадлежит какому-то другому устройству на котором стоит веб сервер (nginx). Проверьте действительно ли с компьютера вы заходите на этот IP. Возможно вы указали двум устройствам один и тот же IP, попробуйте сменить его в ESP устройстве на странице конфигурация:
![2017 10 30-13 24 41](https://user-images.githubusercontent.com/1230815/32168566-d569e65e-bd75-11e7-9dc9-691bd1303828.png)

**Comment by shady2k** [comment]
Ну как бы я уверен, что он принадлежит ESP. Другого устройства с таким IP у меня нет, адреса автоматически назначаются DHCP сервером.

![image](https://user-images.githubusercontent.com/3366415/32168810-0667a044-bd7f-11e7-85e1-ad769aeaa8c1.png)

**Comment by renat2985** [comment]
Понимаете, скриншот который вы мне выслали 100% не может отдавать ESP, в нем нет nginx сервера. Его отдает какое-то другое устройство, которое сидит на этом-же IP, попробуйте в ESP устройстве сменить IP на другой, и перезагрузить ESP.

**Comment by shady2k** [comment]
Теперь понял, спасибо, буду разбираться.

**Comment by shady2k** [comment]
Разобрался, была проблема с маршрутизацией на роутере. Спасибо @renat2985 за помощь.
