### ISSUE TITLE
Разделите RGB & RGBS в разные блоки

### ISSUE THREAD

**Issue by Jawa12** [tretyakovsa/Sonoff_WiFi_switch#94]
На практике замечено что при включении ШИМ в блоке RGBS появляются артефакты в работе блока RGB... Предлагаю разнести их в разные блоки, чтобы не могли однрвременно использоваться. Ну и допилить функционал: на странице управления RGBS не работают ползунки, кнопка включения... Да и вообще последний релиз у меня не загрузился.( В смысле: вебстраница не загрузилась до конца)
Спасибо за проект, но кажется вы его перегружаете функционалом...

**Comment by renat2985** [comment]
Звони, разберемся Skype renat2985

**Comment by tretyakovsa** [comment]
@Jawa12 Это был баг. Исправлено.
