### ISSUE TITLE
Ошибка при сборке проекта

### ISSUE THREAD

**Issue by alxnovo** [tretyakovsa/Sonoff_WiFi_switch#96]
Выручайте, никак теперь не могу собрать проект. Причём не собираются как старые исходники (которые компилировались) так и текущие.

Arduino IDE при компиляции выдаёт вот такую ошибку

![qip shot - screen 009](https://user-images.githubusercontent.com/31793872/44962250-263dc300-af26-11e8-97fd-93353248e299.png)

**Comment by multiminik** [comment]
Поиграйте версиями библиотеки ArduinoJson. Если обновляли на последнюю бетку, то собираться не будет. Отлично собирается на последней релизной версии библиотеки.

**Comment by alxnovo** [comment]
Пробовал даунгрейдить ArduinoJson до стабильных 5-ых версий, тогда при компиляции ругается на WebServer8266, даунгрейдил библиотеки плат, то же на WebServer8266 ругается.
Потратил 3 часа ночью, но даже сборка прошлого года не компилируется, раньше она без вопросов компилировалась.
@tretyakovsa на каких версиях библиотек вы компилируете свой проект?

**Comment by alxnovo** [comment]
Вот такая ошибка при старых версиях библиотек JsonArduino 5.13.12 и ESP8266 Community 2.4.1

![qip shot - screen 010](https://user-images.githubusercontent.com/31793872/45001106-01535980-afd3-11e8-9fd2-828d7cadb5c6.png)

**Comment by alxnovo** [comment]
@tretyakovsa Сергей, спасибо!

Помог даунгрейд до:
       -  ArduinoJson 5.12.0
       -  главное ядро 2.3.0

Компиляция прошла успешно.
